# Generated by Django 4.2.9 on 2024-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="contact", name="show", field=models.BooleanField(default=True),
        ),
    ]
